// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOD1a7yBKMBoxdwuRiDvNAGCTFOreTXeQ',
    appId: '1:690747462870:web:3f66330386b1098f546577',
    messagingSenderId: '690747462870',
    projectId: 'todo-82c27',
    authDomain: 'todo-82c27.firebaseapp.com',
    storageBucket: 'todo-82c27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRuoQWwi7drpOzb1ZgajUTFuiJKAt_EM',
    appId: '1:690747462870:android:f42b142e49134da8546577',
    messagingSenderId: '690747462870',
    projectId: 'todo-82c27',
    storageBucket: 'todo-82c27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj5MZgssRrvmF02mwDeKKJoIy-1Vlva7M',
    appId: '1:690747462870:ios:4aded461e0d383ab546577',
    messagingSenderId: '690747462870',
    projectId: 'todo-82c27',
    storageBucket: 'todo-82c27.appspot.com',
    iosClientId: '690747462870-16drm2rg78gfjn8deghaej37ddfi67t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj5MZgssRrvmF02mwDeKKJoIy-1Vlva7M',
    appId: '1:690747462870:ios:3cc092dcea72688b546577',
    messagingSenderId: '690747462870',
    projectId: 'todo-82c27',
    storageBucket: 'todo-82c27.appspot.com',
    iosClientId: '690747462870-uqq8msahaoub400mh36fakprs7d193at.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
